### ISSUE TITLE
Install fails, missing requirements? Questions (non-admin?). Other feedback with pure pwsh scripts

### ISSUE THREAD

**Issue by arberg** [ModeratelyAverage/ppControl#2]
Hi Mr CEO of ModeratelyAverage, Tough name to spell...

Looks interesnting your script. I like what you are trying to do, I could use that short-hand. 

1) 
I tried installing it (after reviewing the code, and it look harmless enough), and I got this error from line 56 with Add-type  with WpfFluentMaterial (when copied lines one by one, I get this full error:

```
Add-Type: error CS1705: Assembly 'PresentationFramework' with identity 'PresentationFramework, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'WindowsBase, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'WindowsBase' with identity 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
Add-Type: error CS1705: Assembly 'PresentationFramework' with identity 'PresentationFramework, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'WindowsBase, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'WindowsBase' with identity 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
Add-Type: error CS1705: Assembly 'PresentationCore' with identity 'PresentationCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'WindowsBase, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'WindowsBase' with identity 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
Add-Type: error CS1705: Assembly 'PresentationCore' with identity 'PresentationCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'WindowsBase, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'WindowsBase' with identity 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
Add-Type: error CS1705: Assembly 'PresentationCore' with identity 'PresentationCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'WindowsBase, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'WindowsBase' with identity 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
Add-Type: (56,51): error CS7069: Reference to type 'DispatcherObject' claims it is defined in 'WindowsBase', but it could not be found
            HwndSource mainWindowSrc = HwndSource.FromHwnd(mainWindowPtr);
                                                  ^
Add-Type: error CS1705: Assembly 'PresentationCore' with identity 'PresentationCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'WindowsBase, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'WindowsBase' with identity 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
Add-Type: error CS1705: Assembly 'PresentationCore' with identity 'PresentationCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'WindowsBase, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'WindowsBase' with identity 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

This is what I get when executing `ppControl.ps1 -install`
```
Add-Type: D:\Users\Alex\Downloads\ppControl.ps1:56
Line |
  56 |  Add-Type -ReferencedAssemblies $RefAssys -TypeDefinition '
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | error CS1705: Assembly 'PresentationFramework' with identity 'PresentationFramework, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'WindowsBase, Version=8.0.0.0, Culture=neutral,
     | PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'WindowsBase' with identity 'WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

Am I missing some kind of .Net version? Currently I have this one installed on my new Win11 system: `winget install Microsoft.DotNet.DesktopRuntime.8`

2) 

Does it support running as non-admin user? I use RunAsSpc to get elevated permissions when needed, something like that could probably be used to enable it for non-admin support, if not already available.

3)

I tried running some of the functions manually, and some didn't seem to work, like  `Enumerate-PowerPlans`. I noticed it just seems to list all current powerplans, and I already have sscripts for that, so I figured I'll send you those in case you will appreciate the inspiration. Some of it is possible to do directly in pwsh instead of going via powercfg:

Here's a couple of relevant functions (also see attached zip)
```
function getAllPowerPlans
{
	return powercfg /list | sls  -AllMatches -Pattern "Power Scheme GUID: (\w*-\w*-\w*-\w*-\w*)\s*\((.*)\)" | %{ 
      [PSCustomObject]@{
	        Name=$_.matches.Groups.Value[2]
	        Guid=$_.matches.Groups.Value[1]
	    }
	}
}
# Requires Administrator
function getActivatePowerPlanObject
{
    $Filter="isActive='true'"
    Get-CimInstance -Class win32_PowerPlan -Namespace root\cimv2\power -Filter $Filter
}

```

You may use the attached script content as you wish. Some of it is probably useless and tailed for my system, but there's nothing harmful in it.

Best Alex

[AlexPowerPlan.zip](https://github.com/ModeratelyAverage/ppControl/files/14917021/AlexPowerPlan.zip)

**Comment by ModeratelyAverage** [comment]
Hey thanks for taking the time to try out my script! Let me try to address these one at a time:

1. The problem you are experiencing is due to you running the script from modern PowerShell (`pwsh.exe`) instead of Windows PowerShell v5.x (`powershell.exe`). Unfortunately, there are major compatibility issues when running on the newer versions of PowerShell, and I have no plans at this time to rework the script to support them. Everything should work natively on a fresh installation of Windows 11 or higher without installing any additional frameworks or runtimes, although versions of Win 11 lower than 22H2 may have issues with incorrect icons.

```
PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.26100.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.26100.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

2. Yes, this script supports running as non-admin. I worked around the permissions issues by leveraging `powercfg,exe` to manipulate the power settings as there is an existing shim in place for the required resources. No other functions in the script require even a hint of admin rights.
3. Please be aware that some of the functions rely on constants set in the script and they may not execute properly outside of the script if the constants are not also declared. `Enumerate-PowerPlans` is one of those functions as it relys on `$GuidRegEx` and `$NameRegEx`.
If I run the function without declaring the constants, the output is incomplete.
```
PS C:\> Function Enumerate-PowerPlans {
>>     #CIM Cmdlets would be better, but administrative rights would be required. Fallback to parsing powercfg.exe like a chad.
>>     $PCFG_PlanList = cmd /c "powercfg.exe /L"
>>
>>     #Enumerate Power Plans and build reference object
>>     $PowerPlans = @()
>>     #Lines 0-2 are disposable output. Begin at line 3.
>>     $Line = 3
>>     While ($Line -lt $($PCFG_PlanList.Count)) {
>>         $PlanObject = [PSCustomObject]@{
>>             LineIndex = $Line
>>             PlanGuid = [regex]::Match($PCFG_PlanList[$Line],$GuidRegEx).Value
>>             PlanName = ([regex]::Match($PCFG_PlanList[$Line],$NameRegEx).Value).Replace('(',$null).Replace(')',$null)
>>         }
>>         $PowerPlans = $PowerPlans + $PlanObject
>>         $Line++
>>     }
>>     Return $PowerPlans
>> }
PS C:\> Enumerate-PowerPlans

LineIndex PlanGuid PlanName
--------- -------- --------
        3
        4
        5
        6
```
But as soon as I import the constants, the ouput is what is expected 
```
PS C:\> $GuidRegEx = '(\{){0,1}[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}(\}){0,1}'
PS C:\> $NameRegEx = '\(([^)]+)\)'
PS C:\> Enumerate-PowerPlans

LineIndex PlanGuid                             PlanName
--------- --------                             --------
        3 381b4222-f694-41f0-9685-ff5bb260df2e Balanced
        4 725c136c-0832-4ebe-97a8-9e20f431518d Ultimate Performance
        5 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c High performance
        6 a1841308-3541-4fab-bc81-f71556f20b4a Power saver
```
I will take a look at the code you sent, however. I was never a fan of text-parsing the output of `powercfg` (preferring to work with objects instead), and so I am always open to improving things where I can.

In the meantime, please try running the script with `powershell.exe` and let me know if you continue to have any issues.

Thanks!

**Comment by arberg** [comment]
1. Ah, makes sense, I didn't think to try that, though I have also sometimes run into that problem. I check it like this, but it seems you already know that:

$isWindowsPowershell5=$PSVersionTable.PSVersion.Major -eq 5
$isPowershellCore=$PSVersionTable.PSVersion.Major -ge 7

if you wish you could add helpful error at the top
```
$isWindowsPowershell5=$PSVersionTable.PSVersion.Major -eq 5
$isPowershellCore=$PSVersionTable.PSVersion.Major -ge 7
 if (-Not $isWindowsPowershell5) { throw "This script require the Windows Powershell 5, it does not run in newer versions of Powershell" }
 ```
 
 2. Good to hear.
 
 3. Yeah, I missed those two variables when I did my experimentation. It looks fine now.
 
Auw man, it works now, using `Windows Powershell 5`. I'm happy as can be :) I auto-switch in some tasks I have to a no-sleep mode, and then switch back when my tasks are finished to a my default 'windows auto-sleep' task. I have a special task-scheduler that does idle checks and sleeps my pc when I'm AFK too long, because windows built-in sleep just never works for me. So its really nice to be able to switch to my dont-sleep-power-plan without needing to open the 'Power Options' gui. I think your gui looks okay-ish. The empty drop-down is pretty ugly, but I don't care, it works and looks just fine.

Regarding the functions, yeah its nice to sometimes not have to parse powercfg output, though I guess if-it-aint-broken-don't-fix-it. I didn't realize powercfg worked for changing plans without administrator rights. Its a fine solution to just use powercfg then. 

Best Alex
